# Generated by Django 6.1 on 2026-08-29 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(blank=True, help_text='Extracted headline or title', max_length=350)),
                ('news_text', models.TextField(help_text='Full news headline or article text analyzed')),
                ('ml_prediction', models.CharField(help_text='Predicted label: REAL, FAKE, or UNCERTAIN', max_length=50)),
                ('ml_confidence', models.FloatField(help_text='Model confidence score percentage (0-100)')),
                ('real_probability', models.FloatField(default=0.0, help_text='Calibrated probability for Real class')),
                ('fake_probability', models.FloatField(default=0.0, help_text='Calibrated probability for Fake class')),
                ('evidence_status', models.CharField(default='UNAVAILABLE', help_text='SUPPORTING, CONFLICTING, INSUFFICIENT, or UNAVAILABLE', max_length=50)),
                ('evidence_summary', models.TextField(blank=True, help_text='Synthesis of external evidence')),
                ('retrieved_sources', models.JSONField(blank=True, default=list, help_text='List of source articles retrieved')),
                ('final_verdict', models.CharField(help_text='Final user-facing classification status', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prediction History',
                'verbose_name_plural': 'Prediction Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
