# Generated by Django 6.1 on 2026-08-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionhistory',
            name='retrieved_sources',
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='badge_class',
            field=models.CharField(blank=True, default='secondary', max_length=20),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='explanation',
            field=models.TextField(blank=True, help_text='Plain-English explanation of why this verdict was generated'),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='fact_check_status',
            field=models.CharField(blank=True, default='Not Available', help_text='Verified Fact Check result', max_length=50),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='is_current_news',
            field=models.BooleanField(default=False, help_text='Whether the claim concerns breaking/current events'),
        ),
    ]
