# Generated by Django 6.1 on 2026-08-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_remove_predictionhistory_retrieved_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='retrieved_sources',
            field=models.JSONField(blank=True, default=list, help_text='List of source articles retrieved'),
        ),
    ]
